### ISSUE TITLE
Gib BBD daddy

### ISSUE THREAD

**Issue by Myrkie** [nitrog0d/XSOverlay-Discord-Notifications#1]
Gib Better discord version plox

**Comment by nitrog0d** [comment]
no bd bad
https://github.com/niallVR/XSDiscord
not the same tho

**Comment by Myrkie** [comment]
Yes BD good if bad convert all my plugins to powercord :)

**Comment by nitrog0d** [comment]
no bd still bad use bdcompat for powercord if that's the case and hope they're all compatible (which is false hope tbh i can't use most bd plugins)

**Comment by Myrkie** [comment]
hordini just told me to >M< ill try it later :)
