### ISSUE TITLE
Not sending DM or group chat notifications

### ISSUE THREAD

**Issue by TanukiPenny** [nitrog0d/XSOverlay-Discord-Notifications#2]
At first I thought it was not working but it seems to only send notifications from servers. Feel free to close this issue if this is intentional.

**Comment by nitrog0d** [comment]
It should send DM and group messages fine. Make sure you didn't leave the chat open so you can get the notification.
If you notice duplicated names in group dm messages, I'll be pushing a fix as soon as I figure it out

**Comment by TanukiPenny** [comment]
Thanks! So I have tested a bit more, it seems like it won't send them if the discord client is in focus at all. So I just have to make sure to downsize the window it seems.

**Comment by nitrog0d** [comment]
Hmm that's weird, I have no idea what causes that
